ARDUINO_DIR = /usr/share/arduino

USER_LIB_PATH = $(HOME)/sketchbook/libraries

BOARD_TAG = nano328
BOARD_SUB = atmega328old

include /usr/share/arduino/Arduino.mk

.PHONY:arduino
arduino:
	cd ..; make arduino

.PHONY:btn
btn:
	cd ..; make btn

.PHONY:mio
mio:
	cd ..; make mio

.PHONY:gpu
gpu:
	cd ..; make gpu

.PHONY:pi
pi:
	cd ..; make pi

